
export const PLAYERSTEATESHIFT="PLAYERSTEATESHIFT";

export const REQUESTCHANNELLIST="REQUESTCHANNELLIST";

export const RECEIVECHANNELLIST="RECEIVECHANNELLIST";

export const SHOWCHANNELLIST="SHOWCHANNELLIST";

export const UPDATEPLAYLIST="UPDATEPLAYLIST";

export const REQUESTSONG="REQUESTSONG";

export const RECEIVESONG="RECEIVESONG";