
export const PLAYERSTEATESHIFT="PLAYERSTEATESHIFT";

export const SONGTIMEUPDATE="SONGTIMEUPDATE";

export const VOLUMEUPDATE="VOLUMEUPDATE";

export const REQUESTCHANNELLIST="REQUESTCHANNELLIST";

export const RECEIVECHANNELLIST="RECEIVECHANNELLIST";

export const SHOWCHANNELLIST="SHOWCHANNELLIST";

export const UPDATEPLAYLIST="UPDATEPLAYLIST";

export const UPDATEPLAYLISTINDEX="UPDATEPLAYLISTINDEX";

export const UPDATELOCALLIST="UPDATELOCALLIST";

export const REQUESTSONG="REQUESTSONG";

export const RECEIVESONG="RECEIVESONG";

export const KEYWORDCHANGE="KEYWORDCHANGE";

export const REQUESTKEYWORDQUERY="REQUESTKEYWORDQUERY";