
export const PLAYERSTEATESHIFT="PLAYERSTEATESHIFT";

export const SONGTIMEUPDATE="SONGTIMEUPDATE";

export const VOLUMEUPDATE="VOLUMEUPDATE";

export const REQUESTCHANNELLIST="REQUESTCHANNELLIST";

export const RECEIVECHANNELLIST="RECEIVECHANNELLIST";

export const SHOWCHANNELLIST="SHOWCHANNELLIST";

export const FAILQUERYCHANNELLIST="FAILQUERYCHANNELLIST";

export const UPDATEPLAYLIST="UPDATEPLAYLIST";

export const UPDATEPLAYLISTINDEX="UPDATEPLAYLISTINDEX";

export const UPDATEPLAYLISTSONG="UPDATEPLAYLISTSONG";

export const CLEARALLPLAYLIST="CLEARALLPLAYLIST";

export const SHOWPLAYLIST="SHOWPLAYLIST";

export const UPDATELOCALLIST="UPDATELOCALLIST";

export const DELETEFROMLOCALLIST="DELETEFROMLOCALLIST";

export const REQUESTSONG="REQUESTSONG";

export const RECEIVESONG="RECEIVESONG";

export const KEYWORDCHANGE="KEYWORDCHANGE";

export const REQUESTKEYWORDQUERY="REQUESTKEYWORDQUERY";

export const RECEIVEKEYWORDQUERY="RECEIVEKEYWORDQUERY";

export const KEYWORDQUERYFAIL="KEYWORDQUERYFAIL";

export const REQUESTLYRIC="REQUESTLYRIC";

export const RECEIVELYRIC="RECEIVELYRIC";

export const FAILLYRIC="FAILLYRIC";

export const CHANGEPLAYMODE="CHANGEPLAYMODE";


